name: UpCloud Terraform provider acceptance tests

on:
  push:
    branches:
      - master

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.15.x]
    steps:
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - name: install
        run: bash scripts/gogetcookie.sh
      - name: acceptance test
        run: make acctest
